#!/usr/bin/env python3
"""Build the tiny rootfs tree for 8th Circle Linux initramfs.

This intentionally avoids requiring root. Device nodes are injected later by
mkinitramfs.py as cpio metadata.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
from pathlib import Path


def copy_file(src: Path, dst: Path, mode: int | None = None) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    if mode is not None:
        dst.chmod(mode)


def dynamic_deps(binary: Path) -> list[Path]:
    """Return absolute shared-library paths used by a dynamic executable."""
    try:
        proc = subprocess.run(
            ["ldd", str(binary)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
    except FileNotFoundError:
        return []

    out = proc.stdout or ""
    if "not a dynamic executable" in out:
        return []

    deps: set[Path] = set()
    for line in out.splitlines():
        # Handles both:
        #   libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (...)
        #   /lib64/ld-linux-x86-64.so.2 (...)
        for token in re.findall(r"/(?:[^\s()]+)", line):
            p = Path(token)
            if p.exists():
                deps.add(p)
    return sorted(deps)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runtime", required=True, type=Path)
    ap.add_argument("--init-image", required=True, type=Path)
    ap.add_argument("--msh-image", type=Path, help="optional msh image to ship as /bin/msh.mb")
    ap.add_argument("--mfs-image", type=Path, help="optional MFS image to ship as /mfs/root.mfs")
    ap.add_argument("--userland-dir", type=Path, help="directory of generated .mb images to copy into /bin")
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    root = args.out
    if root.exists():
        shutil.rmtree(root)

    for d in ["bin", "sbin", "dev", "proc", "sys", "tmp", "etc", "run", "var/log", "mfs"]:
        (root / d).mkdir(parents=True, exist_ok=True)
    (root / "tmp").chmod(0o1777)

    # The kernel executes /init. Our runtime auto-loads /sbin/init.mb if no argv image is passed.
    copy_file(args.runtime, root / "init", 0o755)
    copy_file(args.runtime, root / "bin/m8", 0o755)
    copy_file(args.init_image, root / "sbin/init.mb", 0o644)
    if args.msh_image:
        copy_file(args.msh_image, root / "bin/msh.mb", 0o644)
    if args.userland_dir:
        for image in sorted(args.userland_dir.glob("*.mb")):
            if image.name == "init.mb":
                continue
            copy_file(image, root / "bin" / image.name, 0o644)
    if args.mfs_image:
        copy_file(args.mfs_image, root / "mfs/root.mfs", 0o644)

    (root / "etc/issue").write_text(
        "8th Circle Linux / M8 initramfs\n"
        "POSIX was not painful enough. Welcome to the eighth circle.\n"
    )
    (root / "README.initramfs").write_text(
        "This rootfs is generated by 8th Circle Linux.\n"
        "The /init binary is the M8 runtime and /sbin/init.mb is the init scroll.\n"
    )

    # If runtime is dynamically linked, bring the loader and libraries into the same absolute paths.
    for dep in dynamic_deps(args.runtime):
        dst = root / dep.relative_to("/")
        copy_file(dep, dst)

    print(f"rootfs ready: {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
